# Generated by Django 4.1.6 on 2023-05-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'AdminUser',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=20)),
                ('fb', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('profilepic', models.FileField(upload_to='mentorImage')),
            ],
            options={
                'db_table': 'Mentor Table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_msg', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=250)),
                ('mentor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.user')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='PatientRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=250)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.user')),
            ],
            options={
                'db_table': 'PatientRequests',
            },
        ),
        migrations.CreateModel(
            name='motivations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=250)),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
            ],
            options={
                'db_table': 'motivation',
            },
        ),
        migrations.CreateModel(
            name='Diary_writings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.user')),
            ],
            options={
                'db_table': 'Dairy_writings',
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.user')),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
    ]
